#!/usr/bin/env python3
# Copyright 2019 Jiří Janoušek <janousek.jiri@gmail.com>
# License: BSD-2-Clause, see file LICENSE at the project root.

"""Command-line interface for nufb"""

import clizy

import nufb
from nufb.build import buildcdk


def version():
    """Print version."""
    print(nufb.__version__)


if __name__ == '__main__':
    clizy.run_funcs(version, buildcdk)
