version: 2.1

executors:
  fedora:
    docker:
     - image: fedora:32
       auth:
         username: $DOCKER_USERNAME
         password: $DOCKER_PASSWORD

commands:

  install-common-deps:
    steps:
      - run:
          name: Install common dependencies
          command: |
            dnf update -y > /dev/null
            dnf install -y \
              gcc \
              gcc-c++ \
              git \
              python3 \
              python3-devel \
              python3-pip
      - run:
          name: Clone flatpak-manifest-update
          working_directory: ~/workdir
          command: |
            git clone https://github.com/tiliado/flatpak-manifest-update.git --depth 500
            python3 -m pip install -r flatpak-manifest-update/requirements.txt

  check-updates:
    parameters:
      manifest:
        type: string
    steps:
      - checkout:
          path: ~/workdir/flatpaks
      - run:
          name: Check manifest
          working_directory: ~/workdir/flatpak-manifest-update
          command: |
            python3 flatpak-manifest-update.py ../flatpaks/manifests/<< parameters.manifest >>

jobs:
  check-cdk-master:
    executor: fedora
    working_directory: ~/workdir
    steps:
      - install-common-deps
      - check-updates:
          manifest: master/eu.tiliado.NuvolaCdk.yml

  check-cdk-experimental:
    executor: fedora
    working_directory: ~/workdir
    steps:
      - install-common-deps
      - check-updates:
          manifest: experimental/eu.tiliado.NuvolaCdk.yml

x-jobs: &jobs
  jobs:
    - check-cdk-master:
        context: docker-hub-tiliado
    # Build with latest stable Vala from git.
    - check-cdk-experimental:
        context: docker-hub-tiliado

workflows:
  version: 2
  build:
    <<: *jobs
  nightly:
    <<: *jobs
    triggers:
      - schedule:
          cron: "0 2 * * *"
          filters:
            branches:
              only:
                - devel

