version: 2
jobs:
  build:
    machine: # for docker --privileged
      image: circleci/classic:latest
    working_directory: ~/workdir
    steps:
      - checkout
      - run: 
          name: Build Nuvola SDK/Platform
          command: |
            docker run \
              --mount src=`pwd`,target=/workdir,type=bind \
              --privileged --name fedora fedora:latest \
              bash -c '
                set -eu;
                export LANG=en_US.UTF-8;
                export LC_ALL=en_US.UTF-8;
                echo Install tools;
                dnf -y update && dnf install -y flatpak flatpak-builder && dnf clean all;
                flatpak remote-add flathub https://dl.flathub.org/repo/flathub.flatpakrepo;
                flatpak install -y flathub org.gnome.Sdk//3.28 org.gnome.Sdk.Debug//3.28 > /dev/null;
                flatpak install -y flathub org.gnome.Sdk.Locale//3.28 org.gnome.Platform.Locale//3.28 > /dev/null;
                echo Done installation;
                cd /workdir;
                echo Building flatpak...;
                flatpak-builder result eu.tiliado.NuvolaSdk.yaml;
                echo Archiving flatpak...;
                tar -czf result.tar.gz result;
                echo Done.
              '
      - store_artifacts:
          path: ~/workdir/result.tar.gz
